-- Script para inserir bairros faltantes de São Paulo
-- Total de bairros: 357
-- Gerado em: 2025-09-09T23:43:57.677Z
-- 
-- IMPORTANTE: Execute este script no Supabase SQL Editor
-- ou via interface de administração

-- Zona LESTE (129 bairros)
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('ÁGUA MARINHA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Água Rasa', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Anália Franco', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Aricanduva', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('AUSTRAL', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Bairro dos Pereiras', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Belém', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Carrão', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Carrãozinho', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Castro Alves', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Catumbi', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('CHACARA CALIFORNIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Corinthians-Itaquera', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Engenheiro Goulart', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('FAZENDA ARICANDUVA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Iguaçu', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Iguatemi', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JADIM HELIAN', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM ALTO ALEGRE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM ALTO ALEGRE (SÃO RAFAEL)', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Anália Franco', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM ARICANDUVA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM ARPOADOR', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM AURORA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Cibele', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM CLAUDIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Colorado', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim da Casa Pintada', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Danfer', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM DAS OLIVEIRAS', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM DO DIVINO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Gianeti', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM INDEPENDÊNCIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Iva', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM JUAZEIRO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM LAJEADO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Marabá', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Melunas', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM NÉLIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM NOSSA SENHORA DO CARMO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM NOVE DE JULHO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Robru', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM ROMANO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM SANTA TEREZINHA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM SANTO ANTÔNIO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Textil', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM TIETÊ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM VERÔNIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('José Bonifácio', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Lajeado', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Mooca Água Rasa', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Mooca Baixa', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARADA XV DE NOVEMBRO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Pari', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE BOTURUSSU', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Parque do Carmo', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE GUARANI', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE MOOCA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Parque Moóca', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE PAULISTANO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Parque São Jorge', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE SÃO LOURENÇO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Parque São Lucas', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE SÃO RAFAEL', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE SAVOI CITY', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Passagem Funda', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PATRIARCA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PENHA FRANÇA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Ponte Rasa', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Quarta Parada', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('São Lucas', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('São Mateus', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('SÃO MATHEUS', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('São Rafael', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Sapopemba', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('SÍTIO DA FIGUEIRA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Usp Leste', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Alpina', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA ALTO PEDROSO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA ANTONIETA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA ARAGUAIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Aricanduva', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA BELA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA CARMOSINA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Carolina', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Celeste', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA CHABILÂNDIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Conceição', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA COSMOPOLITA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Curuça', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA CURUÇA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Dalila', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA DO ENCONTRO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA GUARANI', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA INDEPENDÊNCIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA ITAIM', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Jacui', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA JACUÍ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA JUREMA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA LIBANESA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA LOURDES', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Mafra', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA MESQUITA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA MONTE SANTO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA NHOCUNÉ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Nhocunhé', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA NORMA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA NOVA CURUÇA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA NOVA MANCHESTER', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA NOVA SAVOIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Paranaguá', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA PLANA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA PROGRESSO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Ré', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA RÉ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA REGENTE FEIJÓ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA ROSARIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SANTA CLARA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SANTA CRUZ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Santa Isabel', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SANTANA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SÃO SILVESTRE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Silva Teles', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SÍLVIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Talarico', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA TOLSTÓI', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA ZÉFIRA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA ZÉPHYR', 'São Paulo', 'SP');

-- Zona SUL (91 bairros)
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Alto da Boa Vista', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Barragem', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('BELA MARAJOARA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Brooklin Paulista', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Campo Grande', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Capela', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Centro Empresarial', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Chácara Flora', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('CHACARA INGLESA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('CHACARA KLABIN', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('CHACARA SANTA MARIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('CHACARA SÃO JOÃO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Embura', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Engenho Velho', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('ESTÂNCIA MIRIM', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Grajaú', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Guarapiranga', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Hileópolis', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('IBERAPUERA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Interlagos', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Amália', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM ANA ROSA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Ângela', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM CARAVELAS', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM CELESTE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM DOS LAGOS', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Edda', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Edi', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Glória', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM HELGA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM INGÁ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM ITAPURA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM LEME', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM LEONIDAS MOREIRA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM MACEDÔNIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM MARIA DUARTE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM MARIA ESTELA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM MIRANTE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM MONTE AZUL', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM PALMARES', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM PATENTE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM ROSCHEL', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM SANTA CRUZ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim São Luis', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM SONIA INGÁ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM THOMAS', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM UMARIZAL', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM VERGUEIRO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Marsilac', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('M''Boi Mirim', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Moema', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('MOINHO VELHO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('NOVA ALEXANDRIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARAÍSO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE ARARIBA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Parque Cocaia', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE ESMERALDA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE FONGARO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Parque Grajaú', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Parque Independência', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE REBOUÇAS', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Piraporinha', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Planalto Paulista', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Sacomã', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('São Francisco', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('São João', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('São João Clímaco', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Socorro', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Valo Velho', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VARGEM GRANDE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Veleiros', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Carioca', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA DA SAÚDE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila das Mercês', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA FIRMIANO PINTO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Guaraní', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA GUMERCINDO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA ISA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Joaniza', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA LÚCIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Mercês', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Moinho Velho', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA MOINHO VELHO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA MORUMBI', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA NATÁLIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA PREL', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SANTA CATARINA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SÃO JOSÉ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SOFIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Sta Catarina', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA VERA', 'São Paulo', 'SP');

-- Zona NORTE (75 bairros)
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Alto de Santana', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('América', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Anhanguera', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Anhembi', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Barro Branco', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Cachoeirinha', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Cantareira', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Carandiru', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('CHORA MENINO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('CITY AMÉRICA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Corisco', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Furnas', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Guapira', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Horto Florestal', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Itaberaba', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Anhanguera', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM AURORA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Dayse', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM FRANÇA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM GUAPIRA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM IRIS', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Japão', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM JARAGUÁ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM KIOTO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM PARAÍSO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Peri Peri', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM RECANTO VERDE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim São Bento', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Tremembé', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Vista Alegre', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Lausane Paulista', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Lauzane', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('LAUZANE PAULISTA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('LOTEAMENTO CITY JARAGUÁ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('LOTEAMENTO VISTA VERDE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Morro Grande', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE ANHEMBI', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE MANDAQUI', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Parque Peruche', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Parque Vitória', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PEDRA BRANCA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Perus', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Piqueri', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('SANTA TEREZINHA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('São Domingos', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA ALBERTINA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA AURORA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Cachoeira', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Clarice', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA CONSTANÇA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA DOM PEDRO II', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA EDE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Edi', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Guilherme', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Gustavo', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA JOÃO BATISTA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Mangalot', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Maria', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Maria Baixa', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA MAZZEI', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Medeiros', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA NINA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA NOVA PARADA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA PENTEADO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA PIRITUBA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA PRIMAVERA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Rica', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Sabrina', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SANTA MARIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SANTA TERESINHA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SANTOS', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SIQUEIRA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Zatt', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vista Alegre', 'São Paulo', 'SP');

-- Zona CENTRAL (12 bairros)
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Anhangabaú', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Glicério', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim da Glória', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('LARGO DA MISERICÓRDIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Luz', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Mercado', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Pacaembú', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Parque Dom Pedro I', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Ponte Pequena', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Sé Bela Vista', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA BELA VISTA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA INGLESA', 'São Paulo', 'SP');

-- Zona OESTE (50 bairros)
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Caxingui', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Ceasa', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('CHACARA MARIA TRINDADE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Educandário', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('FAZENDA MORUMBI', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Ferreira', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Bonfiglioli', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM COLOMBO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim D´Abril', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM DAS VERTENTES', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM ESMERALDA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM ESTER YOLANDA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM GILDA MARIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Leonor', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM LEOPOLDINA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM LONDRINA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM PARQUE MORUMBI', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM SANTO ELIAS', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM SARAH', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardim Vera Cruz', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('JARDIM VITÓRIA RÉGIA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Jardins', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Lapa de Baixo', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PACAEMBU', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PAINEIRAS DO MORUMBI', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE ANHANGUERA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE CISPER', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Parque Continental', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE DA LAPA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE DAS FLORES', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('PARQUE NAÇÕES UNIDAS', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Paulista', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Perus', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Raposo Tavares', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Real Parque', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Sumaré', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Anastácia', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA BRASILINA', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA BUENOS AIRES', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA GUEDES', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Hamburguesa', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Jaguara', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA LAJEADO', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA MORSE', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA PIAUÍ', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Pirajussara', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Pompeia', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Remédios', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('Vila Romana', 'São Paulo', 'SP');
INSERT INTO leiloes_imoveis (bairro, cidade, estado) VALUES ('VILA SUZANA', 'São Paulo', 'SP');

-- 
-- Script finalizado!
-- Total de bairros inseridos: 357
-- 
-- Para verificar se os bairros foram inseridos corretamente, execute:
-- SELECT DISTINCT bairro FROM leiloes_imoveis WHERE cidade = 'São Paulo' AND estado = 'SP' ORDER BY bairro;
